version: '3'
services:
  weatherservice: 
    build: './'
    ports:
      - "3000:3000"
      - "5858:5858"      
    links:
      - redis:redis
    depends_on:
      - redis      
  nginxserver: 
    build: './nginx'
    links:
      - weatherservice:weatherservice
    ports:
    - "80:80"
  redis:
      image: 'redis'
      ports:
          - "6379:6379"
      restart: always
      volumes:
        - ./redis:/data