version: '3'
services: 
  substationsservice: 
    build: './'
    ports:
      - "3001:3001"
      - "5858:5858"      
    links:
      - redis:redis
    depends_on:
      - redis      
  nginxserver: 
    build: './nginx'
    links:
      - substationsservice:substationsservice
    ports:
    - "80:80"
    volumes:
    - ./substations-ui/build:/substations-ui
  redis:
      image: 'redis'
      ports:
          - "6379:6379"
      restart: always
      volumes:
        - ./redis/:/data